### ISSUE TITLE
The file "resolver.xml" does not exist

### ISSUE THREAD

**Issue by ucay** [SymfonyId/SymfonyIdAdminBundle#5]
Commit-an hapus resolver ( 2eaccfff0787e936e3e243dd0e0aa6a30175cebf ) menyebabkan error

```
[InvalidArgumentException]
The file "resolver.xml" does not exist (in: xxx/vendor/symfonyid/symfonyid-admin-bundle/DependencyInjection/../Resources/config).
```

karena masih di-load di `/DependencyInjection/SymfonyIdAdminExtension.php`

**Comment by ad3n** [comment]
@ucay : fixed
